version: '2'
services:
  app:
    image: go-tools
    ports:
      - 7000:80
    volumes:
      - ./:/go/src/github.com/events-manager/
    working_dir: /go/src/github.com/events-manager/
    command: go run main.go
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
  dep:
    image: go-tools
    volumes:
    - ./:/go/src/github.com/events-manager/
    working_dir: /go/src/github.com/events-manager/
    command: dep ensure -v
